seeds: [1,]
dataset_name: "SpokenArabicDigits"
inspect_interpolation: true      
save_attention_weights: false     

test_noise_robustness: false
test_noise_levels: [0.0, 0.01, 0.02, 0.05, 0.1, 0.3, 0.5, 0.7]

data_dir: "./data/"
results_dir: "experiment_best_again"
log_dir: "logs"
runs_dir: "runs"
add_time: "no"

num_epochs: 13
batch_size: 2048
time_scaling_factors: ["no"]
tolerances : [0.001]
lr: 0.01                
weight_decay : 0.0001
hidden_dim: 128

experiments_to_run:
  baseline: false
  kernel: false
  gp: false
  qformer: false
  conv: false
  odernn: true
  grud: true
  log_ncde: false

log_ncde_params:
  step_sizes: [20]
  depths: [1]