seeds: [1,2,3,4,5]
dataset_name: "UWaveGestureLibrary"

plot_data: false
add_time: "no"    
test_drop_rates: false          
drop_rates: [0.3, 0.5, 0.7] # Будет использовано 0.0, т.к. test_drop_rates: false

inspect_interpolation: false      
save_attention_weights: false     

test_noise_robustness: false
test_noise_levels: [0.0, 0.01, 0.02, 0.05, 0.1, 0.3, 0.5, 0.7]

data_dir: "./data/"
results_dir: "experiment_mamba_new"
log_dir: "logs"
runs_dir: "runs"

num_epochs: 30
batch_size: 512
time_scaling_factors: ["no"]

# ПАРАМЕТРЫ МАМБЫ (ПОДОБРАНЫ ПО ПАРАМЕТРАМ)
hidden_dim: 132
lr: 0.005
tolerances: [0.001]
weight_decay: 0.00001

mamba_params:
  pscan: true
  n_layers: 2
  d_state: 16
  d_conv: 4
  expand_factor: 2

experiments_to_run:
  mamba: true